Make sure things fail as expected

diff --git a/.github/actions/pybugsai/action.yml b/.github/actions/pybugsai/action.yml
--- a/.github/actions/pybugsai/action.yml
+++ b/.github/actions/pybugsai/action.yml
@@ -27,11 +27,11 @@ runs:
       shell: bash
       run: |
         . ./scripts/venv_github.sh
-        ls -aR .pybugsai
         if ./scripts/pybugsai_github.sh; then
           echo "cache-key-suffix=SUCCESS" >> "$GITHUB_OUTPUT"
         else
-          echo "cache-key-suffix=FAIL" >> "$GITHUB_OUTPUT" 
+          echo "cache-key-suffix=FAIL" >> "$GITHUB_OUTPUT"
+          exit 1
         fi
       env:
         OPEN_AI_API_KEY: ${{ inputs.api-key }}
